---
search_recipe:
  scope_statements:
    - "Decarbonisation efforts in the built environment"
    - "Decarbonising homes through heat pumps and low-carbon heating technologies"
    - "Scaling heat pump adoption and reducing costs for widespread use"
    - "Energy efficiency measures in home insulation and heat pump systems"
    - "Support for policies like the Boiler Upgrade Scheme and Low Carbon Heat Scheme"
    - "Promotion of green technologies including solar, wind, hydrogen, and carbon capture"
    - "Innovations in energy storage and grid capacity for low-carbon heating"
    - "Collaboration with governments and local authorities for supportive frameworks"
    - "Ensuring low-income households have access to low-carbon heating technologies"

  keyword_sets:
    - set_name: "all relevant keywords"
      keywords:
        - "decarbon"
        - "build"
        - "built environment"
        - "home"
        - "house"
        - "low carbon"
        - "energy efficiency"
        - "energy management"
        - "insulation"
        - "retrofit"
        - "smart meter"
        - "smart thermostat"
        - "district heat"
        - "heat network"
        - "heat pump"
        - "heat batteries"
        - "thermal energy storage"
        - "biomass boiler"
        - "biomass heat"
        - "geothermal"
        - "hydrogen heating"
        - "micro CHP"
        - "micro combined heat and power"
        - "solar thermal"
        - "bioenergy"
        - "blue hydrogen"
        - "fuel cell"
        - "green hydrogen"
        - "gray hydrogen"
        - "gray hydrogen"
        - "renewable energy"
        - "wind energy"
        - "wind farm"
        - "wind turbine"
        - "photovoltaic"
        - "solar energy"
        - "solar panel"
        - "climate tech"
        - "green tech"
        - "net zero material"
        - "sustainability"
        - "great british energy"
        - "gb energy"
        - "demand response"
        - "electricity grid"
        - "energy grid"
        - "batteries"
        - "energy storage"
