"""
Parliament Research Briefings Enrichment

This script analyzes research briefings data by performing keyword searches
on both the abstracts and the PDF content from the CSV file generated by
the research_briefings_getter.py module.
"""

import json
import logging
import os
import re
import sys
import tempfile

from typing import Any
from typing import Dict
from typing import List
from typing import Optional
from typing import Set
from typing import Union

import pandas as pd

# Import keyword analysis functions
from discovery_utils.utils.keywords import enrich_keyword_labels
from discovery_utils.utils.keywords import get_keyword_hits
from discovery_utils.utils.keywords import get_keywords
from discovery_utils.utils.keywords import transform_labels_df


# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[logging.FileHandler("research_briefings_analysis.log"), logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


def extract_text_from_pdf(pdf_path: str, max_pages: Optional[int] = None) -> str:
    """
    Extract text content from a PDF file.

    Args:
        pdf_path: Path to the PDF file
        max_pages: Maximum number of pages to extract (None for all pages)

    Returns:
        Extracted text as a string
    """
    # First try pdfplumber which handles complex PDFs better
    try:
        import pdfplumber

        with pdfplumber.open(pdf_path) as pdf:
            # Determine page range
            pages_to_extract = min(len(pdf.pages), max_pages or float("inf"))

            # Extract text from each page
            text = ""
            for i in range(int(pages_to_extract)):
                try:
                    page = pdf.pages[i]
                    page_text = page.extract_text() or ""
                    text += page_text
                    text += "\n\n"  # Add extra newlines between pages
                except Exception as e:
                    logger.warning(f"Error extracting text from page {i+1} in {pdf_path}: {e}")

        return text
    except ImportError:
        logger.warning("pdfplumber not installed, falling back to PyPDF2")
    except Exception as e:
        logger.warning(f"Error using pdfplumber on {pdf_path}: {e}")

    # Fall back to PyPDF2
    try:
        import PyPDF2

        text = ""
        with open(pdf_path, "rb") as f:
            pdf_reader = PyPDF2.PdfReader(f)
            # Determine page range
            pages_to_extract = min(len(pdf_reader.pages), max_pages or float("inf"))

            for page_num in range(int(pages_to_extract)):
                try:
                    page = pdf_reader.pages[page_num]
                    page_text = page.extract_text() or ""
                    text += page_text
                    text += "\n\n"  # Add extra newlines between pages
                except Exception as e:
                    logger.warning(f"Error extracting text from page {page_num+1} in {pdf_path}: {e}")

        return text
    except ImportError:
        logger.error(
            "Neither pdfplumber nor PyPDF2 are installed. Install at least one with: pip install pdfplumber PyPDF2"
        )
        return ""
    except Exception as e:
        logger.error(f"Error extracting text from {pdf_path}: {e}")
        return ""


def load_research_briefings(metadata_file: str) -> pd.DataFrame:
    """
    Load research briefings from a metadata CSV file.

    Args:
        metadata_file: Path to the metadata CSV file

    Returns:
        DataFrame with research briefing data
    """
    try:
        df = pd.read_csv(metadata_file)
        logger.info(f"Loaded {len(df)} research briefings from {metadata_file}")
        return df
    except Exception as e:
        logger.error(f"Error loading research briefings from {metadata_file}: {e}")
        return pd.DataFrame()


def prepare_briefing_data_with_pdf_text(
    df: pd.DataFrame, max_pages: Optional[int] = None, batch_size: int = 10, cache_dir: Optional[str] = None
) -> pd.DataFrame:
    """
    Enhance the DataFrame with text extracted from PDFs in batches.

    Args:
        df: DataFrame with research briefing data
        max_pages: Maximum number of pages to extract per PDF
        batch_size: Number of PDFs to process in each batch
        cache_dir: Directory to cache extracted text (None for no caching)

    Returns:
        DataFrame enhanced with PDF text content
    """
    # Create a copy of the DataFrame to avoid modifying the original
    result_df = df.copy()

    # Create a new column for PDF text if it doesn't exist
    if "pdf_text" not in result_df.columns:
        result_df["pdf_text"] = None

    # Create or ensure cache directory exists
    if cache_dir:
        os.makedirs(cache_dir, exist_ok=True)
        logger.info(f"Using cache directory: {cache_dir}")

    # Filter to only rows with PDF files
    pdf_rows = result_df[result_df["pdf_file"].notna()]
    logger.info(f"Found {len(pdf_rows)} briefings with PDF files out of {len(result_df)} total")

    # Process in batches to manage memory usage
    total_rows = len(pdf_rows)
    num_batches = (total_rows + batch_size - 1) // batch_size

    logger.info(f"Processing {total_rows} PDFs in {num_batches} batches of size {batch_size}")

    # Track stats
    pdfs_processed = 0
    pdfs_from_cache = 0
    pdfs_not_found = 0

    # Process each batch
    for batch_num in range(num_batches):
        start_idx = batch_num * batch_size
        end_idx = min(start_idx + batch_size, total_rows)

        logger.info(f"Processing batch {batch_num+1}/{num_batches} (PDFs {start_idx+1}-{end_idx})")

        # Get the indices from the filtered DataFrame
        batch_indices = pdf_rows.iloc[start_idx:end_idx].index

        # Process each PDF in the batch
        for idx in batch_indices:
            pdf_path = result_df.loc[idx, "pdf_file"]

            # Skip if no path or file doesn't exist
            if pd.isna(pdf_path) or not os.path.exists(pdf_path):
                logger.debug(f"No PDF found for briefing {result_df.loc[idx, 'id']}")
                pdfs_not_found += 1
                continue

            # Check if we have cached text for this PDF
            pdf_text = None
            cache_hit = False

            if cache_dir:
                # Generate a cache filename based on PDF path and max_pages
                pdf_basename = os.path.basename(pdf_path)
                cache_filename = f"{os.path.splitext(pdf_basename)[0]}"
                if max_pages:
                    cache_filename += f"_p{max_pages}"
                cache_filename += ".txt"

                cache_path = os.path.join(cache_dir, cache_filename)

                if os.path.exists(cache_path):
                    try:
                        with open(cache_path, "r", encoding="utf-8") as f:
                            pdf_text = f.read()
                        cache_hit = True
                        pdfs_from_cache += 1
                        logger.debug(f"Using cached text for {pdf_basename}")
                    except Exception as e:
                        logger.warning(f"Error reading cache file {cache_path}: {e}")

            # Extract text if not found in cache
            if pdf_text is None:
                logger.info(f"Extracting text from PDF: {os.path.basename(pdf_path)}")
                pdf_text = extract_text_from_pdf(pdf_path, max_pages=max_pages)
                pdfs_processed += 1

                # Cache the extracted text
                if cache_dir and pdf_text:
                    try:
                        with open(cache_path, "w", encoding="utf-8") as f:
                            f.write(pdf_text)
                        logger.debug(f"Cached extracted text to {cache_path}")
                    except Exception as e:
                        logger.warning(f"Error writing cache file {cache_path}: {e}")

            # Update the DataFrame with the PDF text
            if pdf_text:
                result_df.at[idx, "pdf_text"] = pdf_text

    # Log statistics
    logger.info(f"PDF text extraction completed:")
    logger.info(f"  Total PDFs processed: {pdfs_processed}")
    logger.info(f"  PDFs loaded from cache: {pdfs_from_cache}")
    logger.info(f"  PDFs not found: {pdfs_not_found}")

    return result_df


def prepare_data_for_keyword_analysis(
    df: pd.DataFrame, max_pages: Optional[int] = None, batch_size: int = 10, use_cache: bool = True
) -> pd.DataFrame:
    """
    Prepare the briefing data for keyword analysis, including PDF text.

    Args:
        df: DataFrame with research briefing data
        max_pages: Maximum number of pages to extract per PDF
        batch_size: Number of PDFs to process in each batch
        use_cache: Whether to cache extracted PDF text

    Returns:
        DataFrame ready for keyword analysis with 'id' and 'text' columns
    """
    # Set up cache directory
    cache_dir = None
    if use_cache:
        # Create a temporary directory for cache if not specified
        cache_dir = tempfile.mkdtemp(prefix="pdf_text_cache_")
        logger.info(f"Created temporary cache directory: {cache_dir}")

    # Extract text from PDFs and add to DataFrame
    enhanced_df = prepare_briefing_data_with_pdf_text(
        df, max_pages=max_pages, batch_size=batch_size, cache_dir=cache_dir
    )

    # Create a clean DataFrame with just id and text
    analysis_df = enhanced_df[["id"]].copy()

    # Combine abstract and PDF text
    analysis_df["text"] = enhanced_df.apply(
        lambda row: (str(row["abstract"]) if pd.notna(row["abstract"]) else "")
        + " "
        + (str(row["pdf_text"]) if pd.notna(row["pdf_text"]) else ""),
        axis=1,
    )

    # Remove rows with empty or missing text
    analysis_df = analysis_df[analysis_df["text"].notna() & (analysis_df["text"] != "")]

    return analysis_df


def perform_keyword_analysis(
    df: pd.DataFrame, keyword_type: str = "ASF", analysis_df: Optional[pd.DataFrame] = None
) -> pd.DataFrame:
    """
    Perform keyword analysis on the research briefings.

    Args:
        df: DataFrame with research briefing data
        keyword_type: Type of keywords to use for analysis (e.g., "ASF", "AFS", "AHL", "X")
        analysis_df: Pre-prepared DataFrame for analysis with 'id' and 'text' columns

    Returns:
        DataFrame with keyword analysis results
    """
    logger.info(f"Performing keyword analysis using {keyword_type} keywords")

    if analysis_df is None:
        logger.error("No analysis DataFrame provided")
        return df

    try:
        # Apply keyword enrichment
        logger.info(f"Enriching labels with {keyword_type} keywords...")
        enriched_df = enrich_keyword_labels(analysis_df, keyword_type)

        # Transform labels to get the expected format
        logger.info("Transforming labels...")
        transformed_df = transform_labels_df(enriched_df)

        # Merge the results back to the original DataFrame
        result_df = pd.merge(df, transformed_df, on="id", how="left")

        # Add a column indicating whether keywords were found
        result_df["has_keywords"] = ~result_df["mission_labels"].isna()

        return result_df

    except Exception as e:
        logger.error(f"Error during keyword analysis: {e}")
        raise


def get_detailed_keyword_matches(
    df: pd.DataFrame, keyword_type: str = "ASF", analysis_df: Optional[pd.DataFrame] = None
) -> pd.DataFrame:
    """
    Get detailed information about keyword matches in each document's text.

    Args:
        df: DataFrame with research briefing data
        keyword_type: Type of keywords to use for analysis
        analysis_df: Pre-prepared DataFrame for analysis with 'id' and 'text' columns

    Returns:
        DataFrame with detailed keyword match information
    """
    logger.info(f"Getting detailed keyword matches using {keyword_type} keywords")

    # Get keywords dictionary
    keywords_dict = get_keywords(keyword_type)

    if analysis_df is None:
        logger.error("No analysis DataFrame provided")
        return pd.DataFrame()

    detailed_matches = []

    for idx, row in analysis_df.iterrows():
        try:
            # Get the text to search
            text = row.get("text", "")

            if not text:
                continue

            # Get keyword hits
            hits_df = get_keyword_hits(text, keywords_dict)

            # Process hits
            if not hits_df.empty:
                # Get the original row from df for metadata
                original_row = df[df["id"] == row["id"]].iloc[0] if not df[df["id"] == row["id"]].empty else {}

                # Format the results
                for _, hit_row in hits_df.iterrows():
                    match_info = {
                        "id": row["id"],
                        "title": original_row.get("title", ""),
                        "identifier": original_row.get("identifier", ""),
                        "date": original_row.get("date", ""),
                        "categories": ", ".join(hit_row["category"]),
                        "keywords": [kw for sublist in hit_row["keyword"] for kw in sublist],
                        "sentence": hit_row["sentence"],
                        "marked_sentence": hit_row["marked_sentence"],
                        "match_location": "full_text"
                        if "pdf_text" in df.columns and pd.notna(original_row.get("pdf_text"))
                        else "abstract",
                    }
                    detailed_matches.append(match_info)

        except Exception as e:
            logger.error(f"Error getting keyword matches for {row['id']}: {e}")

    return pd.DataFrame(detailed_matches)


def validate_keyword_matches(matches_df: pd.DataFrame) -> pd.DataFrame:
    """
    Validate that keywords actually appear in the sentences as claimed.

    Args:
        matches_df: DataFrame with keyword matches

    Returns:
        DataFrame with validated keyword matches
    """
    logger.info("Validating keyword matches...")

    valid_matches = []
    invalid_matches = []

    for idx, row in matches_df.iterrows():
        all_valid = True

        for keyword in row["keywords"]:
            # Check if the keyword is actually in the sentence (case insensitive)
            if keyword.lower() not in row["sentence"].lower():
                all_valid = False
                logger.warning(f"Invalid match: '{keyword}' not found in sentence from {row['id']}")
                logger.warning(f"Sentence: {row['sentence']}")
                break

        if all_valid:
            valid_matches.append(row)
        else:
            invalid_matches.append(row)

    logger.info(f"Found {len(valid_matches)} valid matches and {len(invalid_matches)} invalid matches")

    # Return only valid matches
    return pd.DataFrame(valid_matches) if valid_matches else matches_df.head(0)


def analyze_research_briefings(
    metadata_file: str,
    output_dir: str = "analysis_output",
    keyword_types: List[str] = ["ASF", "AFS", "AHL", "X", "Nesta"],
    max_pages: Optional[int] = None,
    batch_size: int = 10,
    use_cache: bool = True,
) -> Dict:
    """
    Analyze research briefings data with keyword analysis.

    Args:
        metadata_file: Path to the metadata CSV file
        output_dir: Directory to save the analysis results
        keyword_types: List of keyword types to use for analysis
        max_pages: Maximum number of pages to extract from each PDF
        batch_size: Number of PDFs to process in each batch
        use_cache: Whether to cache extracted PDF text

    Returns:
        Dictionary with analysis metadata
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Load research briefings from CSV
    df = load_research_briefings(metadata_file)

    if df.empty:
        logger.error(f"No research briefings found in {metadata_file}")
        return {"error": "No research briefings found"}

    # Save the base DataFrame
    base_output_file = os.path.join(output_dir, "research_briefings_base.csv")
    df.to_csv(base_output_file, index=False)
    logger.info(f"Saved base research briefings data to {base_output_file}")

    # Prepare data for keyword analysis (extracts PDF text)
    logger.info("Preparing data for keyword analysis (including PDF text)...")
    analysis_df = prepare_data_for_keyword_analysis(
        df=df, max_pages=max_pages, batch_size=batch_size, use_cache=use_cache
    )

    # Save the analysis DataFrame for debugging
    analysis_output_file = os.path.join(output_dir, "research_briefings_analysis_df.csv")
    analysis_df.to_csv(analysis_output_file, index=False)
    logger.info(f"Saved analysis DataFrame to {analysis_output_file}")

    # Results for each keyword type
    results = {}

    for keyword_type in keyword_types:
        try:
            # Perform keyword analysis
            result_df = perform_keyword_analysis(df, keyword_type, analysis_df)

            # Save results
            output_file = os.path.join(output_dir, f"research_briefings_{keyword_type.lower()}_keywords.csv")
            result_df.to_csv(output_file, index=False)
            logger.info(f"Saved {keyword_type} keyword analysis to {output_file}")

            # Get detailed keyword matches
            matches_df = get_detailed_keyword_matches(df, keyword_type, analysis_df)

            if not matches_df.empty:
                # Validate the matches
                valid_matches_df = validate_keyword_matches(matches_df)

                # Save valid matches
                matches_file = os.path.join(output_dir, f"research_briefings_{keyword_type.lower()}_matches.csv")
                valid_matches_df.to_csv(matches_file, index=False)
                logger.info(f"Saved validated {keyword_type} keyword matches to {matches_file}")

                # Store results
                results[keyword_type] = {
                    "total_briefings": len(df),
                    "briefings_with_keywords": int(result_df["has_keywords"].sum()),
                    "keyword_matches": len(valid_matches_df),
                }
            else:
                logger.info(f"No keyword matches found for {keyword_type}")
                results[keyword_type] = {
                    "total_briefings": len(df),
                    "briefings_with_keywords": 0,
                    "keyword_matches": 0,
                }

        except Exception as e:
            logger.error(f"Error processing {keyword_type} keyword analysis: {e}")
            results[keyword_type] = {"error": str(e)}

    # Save overall metadata
    metadata = {"total_briefings": len(df), "keyword_types": keyword_types, "results": results}

    metadata_output_file = os.path.join(output_dir, "analysis_metadata.json")
    with open(metadata_output_file, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    logger.info(f"Saved analysis metadata to {metadata_output_file}")

    return metadata


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Analyze UK Parliament Research Briefings")
    parser.add_argument("--metadata", "-m", required=True, help="Path to the research briefings metadata CSV file")
    parser.add_argument("--output", "-o", default="analysis_output", help="Output directory for analysis results")
    parser.add_argument(
        "--keywords",
        "-k",
        nargs="+",
        default=["ASF", "AFS", "AHL", "X", "Nesta"],
        help="Keyword types to use for analysis",
    )
    parser.add_argument(
        "--max-pages", type=int, help="Maximum number of pages to extract from each PDF (default: all pages)"
    )
    parser.add_argument(
        "--batch-size", type=int, default=10, help="Number of PDFs to process in each batch (default: 10)"
    )
    parser.add_argument("--no-cache", action="store_true", help="Disable caching of extracted PDF text")

    args = parser.parse_args()

    # Perform analysis
    analyze_research_briefings(
        metadata_file=args.metadata,
        output_dir=args.output,
        keyword_types=args.keywords,
        max_pages=args.max_pages,
        batch_size=args.batch_size,
        use_cache=not args.no_cache,
    )
