from datetime import datetime
from datetime import timedelta
from typing import Literal
from typing import Tuple

import numpy as np
import pandas as pd

from discovery_utils import logging
from discovery_utils.getters import hansard
from discovery_utils.synthesis.policy import llm
from discovery_utils.synthesis.policy import slack
from discovery_utils.utils.keywords import get_keyword_hits
from discovery_utils.utils.keywords import get_keywords
from discovery_utils.utils.llm.mission_check import classify_relevance


DEBATE_URL = "https://www.theyworkforyou.com/debates/?id="
MISSIONS = ["ASF", "AFS", "AHL"]


class HansardData:
    """Class to store Hansard data

    Args:
        debates_df: Debates data (speech texts, minor and major headings of debates)
        labelstore_df: Labels generated by our pipeline (including mission labels)
        parties_df: Party memberships of MPs
    """

    def __init__(self) -> None:
        """Initialise the class"""
        HansardGetter = hansard.HansardGetter()
        self.debates_df = HansardGetter.get_debates_parquet()
        self.labelstore_df = HansardGetter.get_labelstore()
        self.parties_df = _people_party_memberships(HansardGetter.get_people_metadata())


def _debate_url(debate_id: str) -> str:
    """Get the URL for a debate given its ID.

    Works most of the time.
    """
    _debate_id = debate_id.split("/")[-1]
    _debate_id = f'{".".join(_debate_id.split(".")[0:-1])}.0'
    return f"{DEBATE_URL}{_debate_id}"


def _speech_url(speech_id: str) -> str:
    return f'{DEBATE_URL}{speech_id.split("/")[-1]}'


def _people_party_memberships(people_dict: dict) -> pd.DataFrame:
    """Get the most recent party membership for each person

    Args:
        people_dict: The dictionary of people metadata from the Hansard data

    Returns:
        A DataFrame that includes 'person_id' and 'name_org' columns
    """
    orgs_df = pd.DataFrame(people_dict["organizations"])[["id", "name"]]
    return (
        pd.DataFrame(people_dict["memberships"])
        .sort_values("start_date", ascending=False)
        .drop_duplicates("person_id")
        .merge(orgs_df, left_on="on_behalf_of_id", right_on="id", how="left", suffixes=("_", "_org"))
    )[["person_id", "post_id", "start_date", "start_reason", "name_org"]]


def _get_weekly_start_date(end_date: str, weeks: int = 1) -> str:
    """Get the start date for a weekly period ending at the specified end_date

    Args:
        end_date: The end date of the period, in the format "YYYY-MM-DD"
        weeks: The number of weeks to go back

    Returns:
        The start date of the period, in the format "YYYY-MM-DD"
    """
    data_end_date = datetime.strptime(end_date, "%Y-%m-%d")
    weeks_ago = data_end_date - timedelta(weeks=weeks)
    return weeks_ago.strftime("%Y-%m-%d")


def _get_speeches_for_period(Hansard: HansardData, start_date: str, end_date: str) -> pd.DataFrame:
    """Get the speeches for a given period

    Args:
        Hansard: Hansard data object including debates_df, labelstore_df, and parties_df
        start_date: The start date of the period, in the format "YYYY-MM-DD"
        end_date: The end date of the period, in the format "YYYY-MM-DD"
    """
    return (
        Hansard.debates_df.query("date >= @start_date and date <= @end_date")
        .merge(
            Hansard.labelstore_df[["id", "mission_labels", "topic_labels"]],
            left_on="speech_id",
            right_on="id",
            how="left",
        )
        .drop_duplicates(subset=["speakername", "speech"])
        .assign(
            headings=lambda df: np.where(
                df.minor_heading.notna() & (df.minor_heading != ""),  # Check if minor_heading is not empty
                df.major_heading.fillna("") + ": " + df.minor_heading,  # Combine both
                df.major_heading.fillna(""),  # Use only major_heading
            )
        )
        .merge(Hansard.parties_df[["person_id", "name_org"]], on="person_id", how="left", suffixes=("", "_person"))
    )


def _get_debates_headings(debates_df: pd.DataFrame) -> pd.DataFrame:
    """Get the counts of debate speeches by major and minor headings"""
    return (
        debates_df.fillna({"major_heading": "", "minor_heading": ""})
        .groupby(["date", "major_heading", "minor_heading", "headings"])
        .agg(counts=("speech_id", "count"))
        .sort_values("date")
        .reset_index()
    )


def _get_debates_major_headings(debates_df: pd.DataFrame) -> pd.DataFrame:
    """Get the counts of debate speeches by major headings"""
    return (
        debates_df.groupby(["date", "major_heading"])
        .agg(counts=("speech_id", "count"))
        .sort_values("date")
        .reset_index()
    )


def _get_debate_text_and_date(debates_df: pd.DataFrame, debate_title: str) -> Tuple[str, str]:
    """Collate the text of a debate given its title

    Args:
        debates_df: The DataFrame with debates
        debate_title: The title of the debate

    Returns:
        A tuple with the debate text and the dates when the debate took place.
        The debate text is formatted as follows:

        Speaker: Speaker name (Organization)
        Speech text
        -----
        Speaker: Speaker name (Organization)
        Speech text
        -----
        ...

    """
    _debate = debates_df.query("major_heading == @debate_title").sort_values("speech_id").to_dict(orient="records")
    unique_dates = debates_df.query("major_heading == @debate_title").date.unique()
    dates = ", ".join(unique_dates)
    debate_text = debate_title + "\n-----\n"
    for speech in _debate:
        debate_text += f"{speech['speakername']} ({speech['name_org']})" + "\n"
        debate_text += speech["speech"] + "\n"
        debate_text += "-----" + "\n"
    return debate_text, dates


def _relevance_check(
    df: pd.DataFrame, threshold: int = 10, filter: Literal[None, "relevant", "not relevant"] = None
) -> pd.DataFrame:
    """Filter debates by relevance threshold"""
    df = df.assign(relevant=lambda df: df["counts"] >= threshold)
    if filter == "relevant":
        return df.query("relevant")
    elif filter == "not relevant":
        return df.query("not relevant")
    else:
        return df


def _get_speech_context(debates_df: pd.DataFrame, speech_dict: dict) -> str:
    """Get the the previous and next speeches for a given speech"""
    # Locate the speech index
    speech_index = debates_df[debates_df["speech_id"] == speech_dict["speech_id"]].index[0]

    # Retrieve previous, current, and next speech data
    # Quick hack to avoid index out of bounds
    try:
        prev_speech = debates_df.iloc[speech_index - 1]
    except IndexError:
        prev_speech = debates_df.iloc[speech_index]
    current_speech = debates_df.iloc[speech_index]
    try:
        next_speech = debates_df.iloc[speech_index + 1]
    except IndexError:
        next_speech = debates_df.iloc[speech_index]

    # Format and return the speech context
    return (
        f"# PREVIOUS SPEECH\n"
        f"Speaker: {prev_speech.speakername} ({prev_speech.name_org})\n"
        f"Full speech: {prev_speech.speech}\n"
        f"# SPEECH WITH KEYWORDS\n"
        f"Keywords: {speech_dict['keyword']}\n"
        f"Sentences with keywords: {speech_dict['sentence']}\n"
        f"Speaker: {current_speech.speakername} ({current_speech.name_org})\n"
        f"Full speech: {current_speech.speech}\n"
        f"# NEXT SPEECH\n"
        f"Speaker: {next_speech.speakername} ({next_speech.name_org})\n"
        f"Full speech: {next_speech.speech}\n"
    )


def _check_robust_keywords(mission_debates_df: pd.DataFrame, keywords_dict: dict) -> pd.DataFrame:
    """Check the relevance of debates using a robust keyword check"""
    _sentences = []
    _categories = []
    _keywords = []
    for _, row in mission_debates_df.iterrows():
        speech_text = row["speech"].replace("Hon.", "Hon").replace("hon.", "hon")
        hits_df = get_keyword_hits(speech_text, keywords_dict)
        _sentences.append(hits_df["sentence"].to_list())
        _categories.append(hits_df["category"].to_list())
        _keywords.append(hits_df["keyword"].to_list())
    return (
        mission_debates_df.copy()
        .assign(
            sentence=_sentences,
            category=_categories,
            keyword=_keywords,
            n_sentences=lambda df: df["sentence"].apply(len),
        )
        .query("n_sentences > 0")
    )


def _summarise_full_debates(
    mission: str,
    weekly_speeches_df: pd.DataFrame,
    debates_to_summarise_df: pd.DataFrame,
) -> dict:
    """
    Summarise full debates for a given mission

    Args:
        mission: The mission to summarise (eg, 'ASF', 'AFS', 'AHL')
        weekly_speeches_df: The DataFrame with weekly speeches
        mission_debates_major_headings_df: The DataFrame with major headings of debates

    Returns:
        A list of dictionaries with the summarised debates
    """
    # Get unique debate titles
    debate_titles = debates_to_summarise_df.major_heading.unique()

    # Summarise the debates using a LLM
    debate_dicts = []
    not_relevant_titles = []
    for debate_title in debate_titles:
        # Prepare the debate text
        debate_text, debate_date = _get_debate_text_and_date(weekly_speeches_df, debate_title)
        debate_instance = llm.Debate(heading=debate_title, content=debate_text)
        # Check relevance of the debate as a whole (based on number of keyword mentions)
        relevant = classify_relevance(debate_text, mission).relevant
        if relevant:
            logging.info(f"Summarising debate: {debate_title}")
            result = llm.summarise_debate_with_structure(debate_instance)
            # Get debate ID
            debate_id = weekly_speeches_df.query("major_heading == @debate_title").speech_id.iloc[0]
            # Prepare the debate dictionary
            debate_dict = result.model_dump()
            debate_dict["title"] = debate_title
            debate_dict["date"] = debate_date
            debate_dict["url"] = _debate_url(debate_id)
            debate_dicts.append(debate_dict)
        else:
            not_relevant_titles.append(debate_title)
    return debate_dicts


def _check_relevant_speeches(
    mission: str,
    mission_debates_df: pd.DataFrame,
    major_headings_to_check: list,
    speeches_df: pd.DataFrame,
) -> list[dict]:
    """Check the relevance of individual speeches summarise the relevant ones as highlights"""
    relevant_speeches = []
    for major_heading in major_headings_to_check:  # noqa: B007
        speech_dicts = mission_debates_df.query("major_heading == @major_heading").to_dict(orient="records")
        # Go through each speech and check for relevance
        for speech_dict in speech_dicts:
            text = _get_speech_context(speeches_df, speech_dict)
            relevant = classify_relevance(text, mission).relevant
            if relevant:
                summary = llm.summarise_quote(text).summary
                _speech_dict = speech_dict.copy()
                _speech_dict["text"] = text
                _speech_dict["relevant"] = relevant
                _speech_dict["summary"] = summary
                _speech_dict["url"] = _speech_url(speech_dict["speech_id"])
                relevant_speeches.append(_speech_dict)
    return relevant_speeches


def _create_quote_dicts(highlights_dict: dict) -> dict:
    """Create a dictionary of quotes to report in the highlights section"""
    highlights_df = pd.DataFrame(highlights_dict)
    if len(highlights_df) > 0:
        quote_dicts = []
        unique_headings = highlights_df.major_heading.unique()
        # Go through each unique heading and prepare a quote dictionary
        for heading in unique_headings:
            highlights_heading_df = highlights_df.query("major_heading == @heading")
            speech_dicts = highlights_heading_df.to_dict(orient="records")
            quotes = [{"summary": speech_dict["summary"], "url": speech_dict["url"]} for speech_dict in speech_dicts]
            quote_dict = {
                "heading": heading,
                "date": "; ".join(highlights_heading_df.date.unique()),
                "quotes": quotes,
            }
            quote_dicts.append(quote_dict)
    else:
        quote_dicts = []
    return quote_dicts


def _collate_mission_slack_block(
    mission: str,
    debate_dicts: list[dict],
    quote_dicts: list[dict],
) -> list[dict]:
    """Collate the blocks for a mission update message"""
    # Prepare the blocks for the debates' section
    debate_blocks = [slack.debate_summary(debate) for debate in debate_dicts]
    # Un-nest the list of blocks
    debate_blocks = [item for sublist in debate_blocks for item in sublist]
    # Prepare the blocks for the quotes' section
    quote_blocks = [slack.quote_debate_block(quote_dict) for quote_dict in quote_dicts]
    # Un-nest the list of blocks
    quote_blocks = [item for sublist in quote_blocks for item in sublist]
    # Create a mission header block
    blocks = [slack.mission_header(mission)]
    blocks += debate_blocks
    blocks += quote_blocks
    return blocks


def _combine_and_chunk_slack_blocks(
    mission_blocks: list[list[dict]], message_date: str, data_start_date: str, data_end_date: str, chunk_size: int = 49
) -> list[list[dict]]:
    """Flatten and convert the mission blocks into chunks of blocks to send to Slack"""
    # Create a header block
    mission_blocks_flat = slack.message_header(message_date, data_start_date, data_end_date)
    # Combine all mission blocks into a single list
    for blocks in mission_blocks:
        mission_blocks_flat += blocks
    # Chunk the blocks (due to Slack's block limit)
    if len(mission_blocks_flat) > chunk_size:
        n_chunks = len(mission_blocks_flat) // chunk_size + 1
        mission_blocks_chunks = []
        for i in range(n_chunks):
            mission_blocks_chunks.append(mission_blocks_flat[i * 49 : (i + 1) * 49])
    else:
        mission_blocks_chunks = [mission_blocks_flat]
    return mission_blocks_chunks


def _create_mission_update_blocks(
    mission: str,
    speeches_df: pd.DataFrame,
) -> list[dict]:
    """Create a mission update message for the Slack channel

    Args:
        mission: The mission to update (eg, 'ASF', 'AFS', 'AHL')
        speeches_df: The DataFrame with weekly speeches and mission labels
    """
    # Fetch mission keywords from the keywords Google Sheet
    keywords_dict = get_keywords(mission)

    # Select only debates related to one of the missions, and do a robust keyword check
    mission_debates_df = _check_robust_keywords(speeches_df, keywords_dict)

    # Get the major headings of the mission-relevant debates
    mission_debates_major_headings_df = _get_debates_major_headings(mission_debates_df)

    # Filter the debates by relevance (simple threshold of number of keyword mentions)
    debates_to_summarise_df = _relevance_check(mission_debates_major_headings_df, threshold=5, filter="relevant")

    # Summarise the relevant debates
    debate_dicts = _summarise_full_debates(mission, speeches_df, debates_to_summarise_df)

    # Select speeches to report in the highlights section
    highlights_dict = _check_relevant_speeches(
        mission=mission,
        mission_debates_df=mission_debates_df,
        major_headings_to_check=mission_debates_major_headings_df.major_heading.unique(),
        speeches_df=speeches_df,
    )

    # Create quote dictionaries from the highlights
    quote_dicts = _create_quote_dicts(highlights_dict=highlights_dict)

    return debate_dicts, quote_dicts


def _collate_data_signals(
    mission: str,
    debate_dicts: list[dict],
    quote_dicts: list[dict],
) -> list[dict]:
    """Collate the data signals regarding mission updates

    To do: make this function more suited for the general data signal type
    """
    return [
        {
            "mission": mission,
            "type": "policy_debates",
            "signal": debate_dicts,
        },
        {
            "mission": mission,
            "type": "policy_quotes",
            "signal": quote_dicts,
        },
    ]


def create_policy_update_message(
    Hansard: HansardData = None,
    missions: list[str] = MISSIONS,
    message_date: str = None,
    data_start_date: str = None,
    data_end_date: str = None,
    weeks: int = 1,
) -> list[dict]:
    """Create a policy update message for the Slack channel

    Args:
        Hansard: HansardData object with debates_df, labelstore_df, and parties_df.
        message_date: The date of the message (YYYY-MM-DD), also used as the data period's end date.
        data_start_date: The start date of the data period (YYYY-MM-DD).
        data_end_date: The end date of the data period (YYYY-MM-DD).
        weeks: The number of weeks to look back if data_start_date is not provided.

    Returns:
        List of dictionaries containing policy update blocks for Slack
    """

    # Load in Hansard data from S3
    Hansard = Hansard or HansardData()

    # Determine dates
    message_date = message_date or datetime.now().strftime("%Y-%m-%d")
    data_end_date = data_end_date or message_date
    data_start_date = data_start_date or _get_weekly_start_date(data_end_date, weeks=weeks)

    # Get the speeches to use in this update
    speeches_df = _get_speeches_for_period(Hansard, data_start_date, data_end_date)

    mission_blocks = []
    data_signals = []
    for mission in missions:
        # Create mission data signals
        debate_dicts, quote_dicts = _create_mission_update_blocks(mission, speeches_df)
        data_signals.append(_collate_data_signals(mission, debate_dicts, quote_dicts))
        mission_blocks.append(_collate_mission_slack_block(mission, debate_dicts, quote_dicts))

    return _combine_and_chunk_slack_blocks(mission_blocks, message_date, data_start_date, data_end_date)
